#!/bin/bash

set -e

# Configure Brew
./brew/setup

# oh my zsh
if [ ! -d "$HOME/.oh-my-zsh" ]; then
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi

# Configure Lastpass CLI
./lastpass/configure