cask_args appdir: "/Applications"

tap "FelixKratz/formulae"

# enviroment setup
brew "stow"
brew "lastpass-cli"

# system
cask "lastpass" unless system "/Applications/Lastpass.app"
# cask "karabiner-elements" unless system "/Applications/Karabiner-Elements.app"
cask "hammerspoon" unless system "/Applications/Hammerspoon.app"
cask "logitech-options" unless system "/Applications/Logi\ Options.app"
cask "nordvpn" unless system "/Applications/NordVPN.app"

# terminal config
# cask "wezterm" unless system "/Applications/Wezterm.app"
cask "ghostty" unless system "/Applications/Ghostty.app"
# cask "alacritty" unless system "/Applications/Alacritty.app"
brew "jandedobbeleer/oh-my-posh/oh-my-posh"
brew "tmux"
brew "nvim"
cask "font-jetbrains-mono-nerd-font"
# cli tools
brew "git"
brew "thefuck"
brew "fd"
brew "fzf"
brew "tldr"
brew "zoxide"
brew "bat"
brew "git-delta"
brew "eza"
brew "tig"
brew "tree"
brew "jq"
brew "yq"
brew "sl"
brew "lazygit"
brew "grep"
brew "ripgrep"
brew "gum"
brew "glow"
brew "gawk"
brew "gnu-sed"
brew "shellcheck"
brew "ranger"
brew "neofetch"

# tunneling
cask "ngrok"

# Window Manager
cask "nikitabobko/tap/aerospace" unless system "/Applications/Aerospace.app"
brew "FelixKratz/formulae/sketchybar"
brew "FelixKratz/formulae/borders"

# productivity
cask "raycast" unless system "/Applications/Raycast.app"
cask "arc" unless system "/Applications/Arc.app"
cask "notion" unless system "/Applications/Notion.app"
cask "shortcat" unless system "/Application/Shortcat.app"

# communication
cask "zoom" unless system "/Applications/zoom.us.app"
cask "whatsapp" unless system "Applications/WhatsApp.app"

# ios
brew "xcodes" unless system "/Applications/Xcodes.app"
brew "mise"